### ISSUE TITLE
Rename "getEnvs" action?

### ISSUE THREAD

**Issue by carmelocatalfamo** [20tab/react-ts-continuous-delivery#22]
Perhaps it would be better to rename "getEnvs" action to "setEnvs" or "changeEnvs"

https://github.com/20tab/react-ts-continuous-delivery/blob/00e82e744df8ae9987b17a9f893949343c275aec/%7B%7Bcookiecutter.project_dirname%7D%7D/store/utilsSlice.ts#L30

**Comment by daniele20tab** [comment]
Issue solved in commit `6e9f475a890f99ab5990fd4d20e840ce36a94ee5`
