### ISSUE TITLE
Update warn about some unused params

### ISSUE THREAD

**Issue by carmelocatalfamo** [20tab/react-ts-continuous-delivery#23]
https://github.com/20tab/react-ts-continuous-delivery/blob/00e82e744df8ae9987b17a9f893949343c275aec/%7B%7Bcookiecutter.project_dirname%7D%7D/package.json#L106-L111

After an upgrade this now could be:
```json
"@typescript-eslint/no-unused-vars": [
  "warn",
  {
    "argsIgnorePattern": "^_",
    "varsIgnorePattern": "^_"
  }
]
```

**Comment by daniele20tab** [comment]
Issue solved in commit `ae73c6bf1b3294e6c5a047caae78af86fe90e50e`
